[db]
    type = "mysql"
    addr = "127.0.0.1"
    port = 3306
    username = ""
    password = ""
    database = "db_weibo"
    charset = "utf8"

[mail]  #SMTP
    user = ""
    pass = "" # 定义邮箱服务器连接信息，如果是阿里邮箱 pass填密码，qq邮箱填授权码
    to   = ["xxx@qq.com"] # 发送到的邮箱

[weibo]
    uid = "" # 微博用户的uid
    containerid = "" # 微博的containerid